### ISSUE TITLE
Support for non boolean validation results?

### ISSUE THREAD

**Issue by kageiit** [hzsweers/inspector#16]
There might be cases where one would want to return more than just a boolean (think an enum) for the validation logic.

It could be possible to extend the Validator interface/make a new one that can return a new type V as the validation result.

**Comment by hzsweers** [comment]
What would be the benefit of that vs just making your own custom ValidationException?

**Comment by hzsweers** [comment]
Not against it just yet, just don't think it would be trivial and it also conflates a bit with the try/catch intention

**Comment by kageiit** [comment]
Did not notice the exception in the api, but even then the exception is a weird way to surface the actual intent. It would seem the API is not designed for such use cases, which is fine, but the exception workaround is a bit weird. maybe if many consumers do the same, this can be reconsidered

**Comment by hzsweers** [comment]
Possibly, the idea is mainly that you can subclass it with whatever you want or put whatever you want in the message. If we made it the return type, I think it'd be better to keep it simple with some holder type with boolean `isValid` and a list of error strings. I'd be worried about the API being a bit cumbersome if it were generic. Want to write up a sample of what you're thinking?

**Comment by hzsweers** [comment]
@kageiit ping

**Comment by kageiit** [comment]
Oops, totally missed your last comment. I will put up a sample tomorrow on how this might work

**Comment by kageiit** [comment]
Consider this case

Upstream service requests location permissions for a dynamic feature. Ideally both `COARSE` and `FINE`. But will work in reduced capacity if only COARSE is available. (Similar example with authentication methods, Feature can request fingerprint sensor, but can work with a PIN as well)

In the current model,

```
public final class PermissionsValidator extends Validator<Feature> {
  @Override public void validate(Feature object) throws PermissionValidationException { }
}
```

It is not clear what is the best way to express validation logic. One can either
- Return true if all conditions are met and false if not
- Return true if any condition is met and deal with it by adding extra logic outside the validation
- Throw an exception or just not use this library to deal with this particular model

Alternatively,
a validator could return an enum for example
```
try {
  switch(inspector.validator(Foo.class).validate(featureInstance)) {
    case ALL: break;
    case SUBSET: break;
    case INVALID: break;
  }
} catch (ValidationException e) { }
```

where `ALL` and `SUBSET` are cases where other validators succeeded and returned a valid enum to deal with appropriately. `INVALID` is when there was a validation error in one of the validators.

the default return can still be boolean and would let the consumers compose their validators appropriately.

**Comment by hzsweers** [comment]
There's a new `SelfValidating` class. I think that should be used for more fine grained validation. As far as levels of validation though, I don't think there's much we can do beyond just allowing people to return a subclass of ValidationException with whatever data they want. From your example:

```java
class FooValidationException extends ValidationException {
    enum Level {
        ALL, SUBSET, INVALID
    }
}

class FooValidator implements Validator<Foo> {
  // validation logic
}
```

It does still route through exception handling, but if one's worried about perf handling, they could override `fillInStacktrace()` to no-op and use it purely as signaling. I'd personally probably say Inspector probably isn't the best use case for this kind of management though.

Does that sound reasonable to you?

**Comment by kageiit** [comment]
Sounds reasonable :)
